### ISSUE TITLE
Security scoped url

### ISSUE THREAD

**Issue by romangish** [IHEARTCOOKIES/XMPFramework#1]
I have a problem opening the security scoped url of the files that I selected through the uidocumentpickerviewcontroller.  I call startAccessingSecurityScopedResource () and use file coordinator to perform read or write operations, but when I call the XMPReader initializer with url, I don’t have access to the file.  Although I can access the file through the Data initializer (contentOf: URL), getting the Data object, and then initialize the XMPReader with Data.  What could be the problem?

**Comment by IHEARTCOOKIES** [comment]
Hi there,

I first off want to apologize for the delay in my response. I haven't had notifications setup until just now, and this must've gotten lost in my email somewhere.

Anyhow, if you're still experiencing the issue, would you mind attaching a small example that I could use to better understand the issue?

**Comment by Wolf00Bomber** [comment]
Crash is happening at this initialisation:
`XMPBatchWriter *writer = [[XMPBatchWriter alloc] initWithFilePath:path];`
The path being 
`file:///var/mobile/Containers/Data/Application/2XXXXXX8-3XX4-4XX0-BXXD-AXXXXXXDCXXE/Library/NoCloud/2020-05-13T165647.jpg`

See Attached Image:
![Screenshot 2024-05-16 at 10 44 33 PM](https://github.com/IHEARTCOOKIES/XMPFramework/assets/2338988/ca77746a-3f24-4c59-99f7-fa0f2a7d7c6e)

**Comment by IHEARTCOOKIES** [comment]
This issue should be fixed in the latest revision. Thank you for your patience!
