### ISSUE TITLE
Crashing on RAW file

### ISSUE THREAD

**Issue by widgt** [IHEARTCOOKIES/XMPFramework#3]
Hi there,

Attempting to read/write RAW files (CR2, ORF) crashes with:

Assertion failed: ((clientIO == 0) ? (clientPath[0] != 0) : (clientPath[0] == 0)), function DoOpenFile, file /Users/filipbusic/Desktop/Adobe-XMP-ToolKit/XMPFiles/source/XMPFiles.cpp, line 940.

**Comment by IHEARTCOOKIES** [comment]
Sorry for the delay, this issue should be fixed now. Feel free to reopen if the issue remains.

**Comment by widgt** [comment]
Thank you!
