### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by Wolf00Bomber** [IHEARTCOOKIES/XMPFramework#5]
I was able to use your Framework, but since it supports only `armv7`, and the modern iPhones all are on `arm64`, I am getting errors using the Framework.

Note: I was able to do pod install, but then in runtime, the App Crashes when I give it a Image path and try to initialise the XMPWriter.

**Comment by Wolf00Bomber** [comment]
I have raised the errors I faced in this Issue:
https://github.com/IHEARTCOOKIES/XMPFramework/issues/1#issuecomment-2115805428

**Comment by IHEARTCOOKIES** [comment]
The framework has been updated to support arm64. Thank you!
